#!/usr/bin/env python3
import json
import typer
import pathlib
import asyncio
import db as database
from rich.console import Console
from rich.panel import Panel
from ext.config import DEFAULT_CONFIG
from typing import Annotated
from main import main as start_codygen
from ext.math import level_to_xp, LevelConverterV3
# from extensions.api import main as start_api
# original cli tool from https://github.com/tjf1dev/protochat


VERSION = open("VERSION", "r").read()
console = Console()

app = typer.Typer()
db = typer.Typer()


@app.callback(invoke_without_command=True)
def main(ctx: typer.Context):
    if ctx.invoked_subcommand is None:
        console.print(
            Panel(
                f"[purple bold]codygen {VERSION}[/purple bold]",
                border_style="purple",
            )
        )
        console.print(
            Panel(
                "[yellow]provide a command first. please use './codygen setup' before any other commands[/yellow]",
                border_style="yellow",
            )
        )


@app.command()
def setup(force: Annotated[bool, typer.Option("--force", "-f")] = False):
    if pathlib.Path("config.json").exists() and not force:
        console.print(
            Panel(
                "[yellow]a config file already exists! no changes have been made, use -f to make a config anyway[/yellow]",
                border_style="yellow",
            )
        )
        return
    console.print(Panel("creating a config..."))
    json.dump(DEFAULT_CONFIG, open("config.json", "w"), indent=2)
    console.print(
        Panel(
            f"[green]...done!\n[cyan]{json.dumps(DEFAULT_CONFIG, indent=2)}[/cyan]\nstart codygen with ./codygen run[/green]",
            border_style="green",
        )
    )


@app.command()
def run():
    start_codygen()


@app.command()
def api():
    from extensions.api import main as run_api

    run_api()


db = typer.Typer()


@db.command()
def create():
    asyncio.run(database.create_table())


@db.command()
def add_column():
    asyncio.run(database.add_column())


@db.command()
def recreate():
    asyncio.run(database.backup_and_recreate())


@db.command()
def convert():
    asyncio.run(database.convert_from_json())


@app.command(name="level_to_xp_v4")
def level_to_xp_v4(level: int):
    print(level_to_xp(level))


@app.command(name="xp_to_level_v4")
def xp_to_level_v4(xp: int):
    print(level_to_xp(xp))


@app.command(name="level_to_xp")
def level_to_xp_cmd(level: int):
    converter = LevelConverterV3(level=level)
    xp = converter.xp
    print(xp)


@app.command(name="xp_to_level")
def xp_to_level_v5(xp: int):
    print(LevelConverterV3(xp).level)


@app.command(name="xp_to_level_chart")
def xp_to_level_chart_v5():
    LevelConverterV3().chart()


app.add_typer(db, name="db")
# @app.command()
# def api():
#     asyncio.run(start_api())


if __name__ == "__main__":
    app()
