name: bug
title: 🐛 Report a bug
description: found an error? report it here!
labels:
  - unconfirmed bug
body:
  - type: dropdown
    id: dropdown-0
    required: true
    attributes:
      label: how did you find this issue?
      options:
        - codygen error message ("an error occured while trying to run this
          command")
        - application did not respond
        - feature didnt work as expected
        - other
  - type: input
    id: input-1
    attributes:
      label: what command did you find the issue in?
      placeholder: 'hint: use the "command" value if you have an error message'
    required: true
  - type: textarea
    id: textarea-2
    attributes:
      label: what did you expect to happen
    required: true
  - type: textarea
    id: textarea-3
    attributes:
      label: what happened
    required: true
